### ISSUE TITLE
Browser throttling likely messing up progress bar

### ISSUE THREAD

**Issue by AndrwMan** [cse110-fa22-group4/cse110-fa22-group4#101]
Progress is no longer correctly synced if electron app is not in focus. Specifically the progress bar is slower than true song progress.  Browsers can throttle setInterval() to 1 second ignoring the original delay specified in the code if tab is inactive and this may the issue here, especially because I am updating every 50 ms. Of course any functionality that relies on progress bar to check if a song is done will be broken too.

**Comment by TheFProjects** [comment]
There's a function in ffmpegAPI that allows you to return the current time of the song, and you can use that that update every time hopefully. It's getCurrentTime()

**Comment by AndrwMan** [comment]
The thing is I would still need to getCurrentTime() every few ms so I still use setInteval() and have the problem. Don't worry for now,  its a frontend thing and I might have a solution

**Comment by AndrwMan** [comment]
Soln: on window focus and unfocus calculate time elapsed and add back the timeAway to saved msElapsed (= place the song was at before user unfocused the app)
