### ISSUE TITLE
Song path locations for playback

### ISSUE THREAD

**Issue by RealHumanBeen** [cse110-fa22-group4/cse110-fa22-group4#113]
A few things that may help playback as it currently stands:

1. for the selected track(s) that can be added to the queue via the main header's queue button, it is currently returned in an array of track objects, which holds the path for each. [here](https://github.com/cse110-fa22-group4/cse110-fa22-group4/blob/8ec8612332edc756c98744d8452ca79d3454937a/source/musicplayer/renderer/components/mainHeader.js#L34)
2. for a single track that can be added to the queue via the track row's queue button, it is returned [here](https://github.com/cse110-fa22-group4/cse110-fa22-group4/blob/8ec8612332edc756c98744d8452ca79d3454937a/source/musicplayer/renderer/components/library.js#L9) if it came from the library grid or [here](https://github.com/cse110-fa22-group4/cse110-fa22-group4/blob/8ec8612332edc756c98744d8452ca79d3454937a/source/musicplayer/renderer/pages/libraryPlaylists.js#L10) if it came from a playlist grid.
3. for playing a track immediately upon clicking a row, the path is returned [here](https://github.com/cse110-fa22-group4/cse110-fa22-group4/blob/8ec8612332edc756c98744d8452ca79d3454937a/source/musicplayer/renderer/components/library.js#L5) if it came from the library grid or [here](https://github.com/cse110-fa22-group4/cse110-fa22-group4/blob/8ec8612332edc756c98744d8452ca79d3454937a/source/musicplayer/renderer/pages/libraryPlaylists.js#L6) if it came from a playlist grid. (note: we may not end up using this because the way gridJS works, clicking a row is so sensitive that even doing options 1 or 2 mentioned above triggers this option for some reason).

**Comment by AndrwMan** [comment]
As stated previously song artist, title, duration and path is the bare minimum for playback functionalities to work. An array of paths for example is not usable. Just add to a singular queue that is an array of objects, each object either regular Js object or Map. 
Ex: `queue = [ {...}, {...}, Map, {...}, Map,   ]`
If it is a single song, then add it as {...}
If it is a playlist, then add it as Map (the structure we discussed)
You should already have the artist, title, duration fields so it shouldn't be hard to format them.
If I have time I can just handle the entire adding to queue and playback end-to-end tbh

**Comment by AndrwMan** [comment]
Actually there might even be an easier way. If we structure queue like the following, playback will just work from its current implementation
If I ignore the first idea, and let the queue be a playlist (which is a Map name queuePlaylist). 
If it is a single song, then just append new song (object {...}) to the end of tracklist array in the queuePlaylist 
If it is a playlist, then append that playlist's tracklist array to the end of the tracklist array in the queuePlaylist

**Comment by RealHumanBeen** [comment]
Responding to the first way: Yes, selecting 1 or multiple songs via the checkboxes and pressing the "+ Queue" button gives you an array of track objects, `[{...}, {...}, ...].` There is no option for queueing an entire playlist currently because we are having some problems still getting it to work. But yes, I will attempt to serve it up as a map if possible. The two other potential methods of adding songs to the queue (1. clicking a track row, 2. click the "+" button at the end of a given row), return song paths atm because gridJS is a bit restricting with passing information using these click functions, but like i said, i will attempt to get it to give you the entire track object. But right now the #1 option using the '+ Queue' button is what you need isn't it? Having access to those track objects should allow you to do the second way as well right?

**Comment by AndrwMan** [comment]
I strongly suggest we use the second method now in case maybe I was vague (completely ignore the first). There will just be a single global map object that represents the queue. It will look like this
```
queueMap.set( 'queuePlaylist', {
	name: 'queuePlaylist',
	numTracks: 0,
	artworks: [],
	trackList: []
});
```
every time you ...
...add a single song you want to push an object into trackList
...add a playlist it concats the playlist's tracklist to the queue playlist's tracklist (ie: Array.prototype.concat())

**Comment by RealHumanBeen** [comment]
Sure, that looks good to me. But like I said, the `+ Queue` button will give you an array of the track objects with all its information (title, artist, duration, the path, etc.) and you can write whatever function you need to implement adding those track objects to your queueMap. Or if you have a place where I can access this queueMap setup, I can take those returned track objects as I mentioned are [here](https://github.com/cse110-fa22-group4/cse110-fa22-group4/blob/8ec8612332edc756c98744d8452ca79d3454937a/source/musicplayer/renderer/components/mainHeader.js#L34) and append them to the `trackList` in this queueMap.

**Comment by AndrwMan** [comment]
Yes, since you have the array already you can just easily append. I can also write the function to append, sure, but that requires me to change your code a little bit with queue buttons probably. You should just be able to access queueMap from your file since its global (but I'm not genAPI publishGlobal works properly, thats another issue entirely). I'll push code rn with that global queue

**Comment by AndrwMan** [comment]
Update: Agreed to use array of objects (each object a song).
