### ISSUE TITLE
Saved theme color not loading on app start

### ISSUE THREAD

**Issue by RealHumanBeen** [cse110-fa22-group4/cse110-fa22-group4#116]
Currently after a theme was picked out from the settings menu, the next time the app is opened the theme reverts to default colors instead of the last saved theme. Only after going back to the settings menu is the last saved theme restored.

The location where the theme color is set upon app start is [here](https://github.com/cse110-fa22-group4/cse110-fa22-group4/blob/8ec8612332edc756c98744d8452ca79d3454937a/source/musicplayer/css/sidebar.css#L21).

**Comment by owadg** [comment]
This has been rectified, however, I cannot seem to set the theme colors until the sidebar has been loaded, but then I cannot change the variable without a flash of the old style.
