### ISSUE TITLE
Button to clear queue

### ISSUE THREAD

**Issue by RealHumanBeen** [cse110-fa22-group4/cse110-fa22-group4#122]
May possibly integrate a button that would clear a user's entire queue.

**Comment by RealHumanBeen** [comment]
button added and will currently clear the contents of the playback queue. this is also reflect in the queue viewer. however not sure what else needs to be updated in playback to reset to a default state of an empty queue. Function that implements queue clear is [here](https://github.com/cse110-fa22-group4/cse110-fa22-group4/blob/359d11c6a937cad9eae077f796786721b1a6e335/source/musicplayer/renderer/components/queueViewer.js#L96).

**Comment by countpearsauce** [comment]
Works good in dev
