### ISSUE TITLE
UI Implementation Focus

### ISSUE THREAD

**Issue by RealHumanBeen** [cse110-fa22-group4/cse110-fa22-group4#44]
The following are pages are the current focus of UI implementation:

- [x] #63
- [x] #64
- [x] #65
- [x] #67

**Comment by owadg** [comment]
Home page updated to just display random artists, genre, tags, albums in commit #c6309e7e848c441fc24c1fcbc3f524f553a77e15

**Comment by owadg** [comment]
This is now finished.
