### ISSUE TITLE
Playback Bar UI

### ISSUE THREAD

**Issue by RealHumanBeen** [cse110-fa22-group4/cse110-fa22-group4#63]
Implementation of playback bar visuals. The playback components will include the following:

- shuffle
- repeat
- previous track
- next track
- pause/play
- progress bar (with track progress and duration 00:00 format)
- volume fader + icon
- now playing album artwork + now playing track info

**Comment by AndrwMan** [comment]
Pushed playback bar visuals. Play and Pause functionality works but need to give a path to the song and set path for ffplay.exe beforehand. Resume does not currently work. Ignore all the comments used for testing dummy songs.
