### ISSUE TITLE
`fsAPI.writePlaylist` and `fsAPI.readPlaylist` seems to throw error

### ISSUE THREAD

**Issue by AndrwMan** [cse110-fa22-group4/cse110-fa22-group4#81]
Problem:
Using `fsAPI.writePlaylist` and `fsAPI.readPlaylist` to create playlist seems to throw `Uncaught (in promise) Error: Cannot read properties of undefined (reading 'join')`. Since the issue is related to join checked the function implementations but 
* `storagePath` is given by electron so it shouldn't be undefined
* `'playlists'` is just a string
* `playlistName` is also just a passed string

Actually the issue may be `path` is undefined. Not sure if I have to set some path again before function call. 
Working playlist api is likely needed to have working prev, next, shuffle buttons.

**Comment by pika-chu11** [comment]
I don't know why I fail to commit the changes. But you can try to solve it by removing the {} surrounded by the variable path and fs at the top of their declaration.
