### ISSUE TITLE
Automatically play next song (and update displayed song data)

### ISSUE THREAD

**Issue by AndrwMan** [cse110-fa22-group4/cse110-fa22-group4#99]
Problem: Currently nothing happens when current song ends. A lot of players have functionality to play next song in playlist when current song ends. At a glance playSong() doesn't indicate when song ends (in fact the progress keeps running after song ends). Discussing with backend how the end of song should behave in general.
 
- [x] Automatic playback for nextSong
- [x] Automatic data display update

**Comment by TheFProjects** [comment]
Andrew(and front end in general), I saw your recent issue and I have a solution that I put on the backend channel earlier that I think we should try out. In the child_process docs, we have this line: ps.on('close', (code) => {//do something}). When the function is closed, call the callback. I think I can have a function that takes a callback and puts it in there for each ffplay instance. However, I think killing it counts as closing, so we have to be careful.  We can use the exit codes if possible. If not, then we'll use a flag, which is inconvenient, but that's plan B.

**Comment by AndrwMan** [comment]
Soln: 
* Currently setInterval() is used to update progress anyways every 50ms so add a check in it for song end then call functions
* handled case with no artwork (assumed empty string), other than that be careful that current dir starts at html for imgs
